baseURL = '/'
languageCode = 'en-us'
title = 'Prine'
theme = "prine"

[params]
    twitterURL = "https://twitter.com/krisnova"
    twitterText = "@krisnova"
    githubURL = "https://github.com/kris-nova"
    githubText = "kris-nova"
    discordURL = "https://discord.com/invite/QG27kwx4nf"
    discordText = "Join our official Discord!"
    youtubeURL = "https://www.youtube.com/channel/UCRvH2UexTzcbZRwCS6OxJ3w"
    youtubeText = "Official YouTube channel!"
    settingsURL = "https://nivenly.com"
    settingsText = "Tweak your site's settings."



[languages]
    [languages.en]
        description = "Prine is a hugo theme based on Nivenly.com"
        title = "Prine - Terminal Inspired Hugo Theme"
        subtitle = "Based on the theme from Nivenly.com"
        keywords = "Kris Nova, krisnova, Nóva, Nova, Hugo, Theme, Terminal, Hacker"
        copyright = "2021 Kris Nóva"

[languages.en.params.logo]
    logoUser = "nova"
    logoHost = "prine"

[languages.en.menu]
    [[languages.en.menu.main]]
        identifier = "src"
        name = "src"
        url = "/src"
    [[languages.en.menu.main]]
        identifier = "lib"
        name = "lib"
        url = "/lib"
    [[languages.en.menu.main]]
        identifier = "readme"
        name = "readme"
        url = "/readme"
